= Pflichtenheft
Peter Klose, Mona Angerer, David Thaller Al Sabagh Abdulrahman
1.0.0, 2021/22

ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:stylesdir: style

== Ausgangssituation

Ein Lehrplan wird für einen Schultyp und eine Spezialisierung gemeinsam von Lehrern und dem Bildungsministerium gestaltet.

Ein Lehrplan wird nur alle 5 - 10 Jahre aktualisiert, während sich bspw. Technologien viel schnelllebiger ändern können.

Ein Lehrplan ist für eine Schule des betreffenden Schultypens und der dazu passenden Spezialisierung bindend.
Dies betrifft sowohl das Stundenausmaß bzw. die geforderten Inhalte und Kompetenzen, aber nicht wie bspw.
die Unterrichtsgegenstände heißen müssen und wie sie intern organisiert sind.

== Istzustand

Die Lehrpläne der Schultypen und Spezialisierungen können derzeit nur statisch,
z.B. auf https://www.ris.bka.gv.at aufgerufen werden. Die Schulinternen Lehrpläne werden
in einem Excel-file dargestellt und bearbeitet.

== Problemstellung

Die rein statische Darstellung der Lehrpläne mit Schultyp, Fachrichtung, Anzahl der Schuljahre, Semesterunterteilung, Beschreibung,
Kommentaren, Kompetenzen und Lehrzielen ist unübersichtlich und benötigt viele verschiedene Seiten.
Das Bearbeiten schulinterner Lehrpläne mittels eines Excel-files ist kompliziert und nicht leicht überschaubar.


== Aufgabenstellung

Folgende Funktionalitäten muss das Lehrplan-Administratormodul zur Verfügung stellen:

* *Workflow* erkennen und ändern (Status : "in Bearbeitung, "Freigegeben")
* *Stammdaten* der allgemeinen Lehrplänen erfassen und die der Schulspezifischen Lehrplänen ändern und löschen (wenn Status auf "in Bearbeitung")
** Für welchen *Schultyp* ist der Lehrplan verfügbar?
** Für welche *Fachrichtung* gilt dieser Lehrplan?
** Für *wie viele Schuljahre* ist der Lehrplan gedacht?
** Welche *Semesterunterteilung* hat dieser Lehrplan?
** Eine *kurze Beschreibung* des Lehrplans in Textform
** Ein Feld für *allgemeine Kommentare* seitens des Lehrplanadministrators
* Folgeversionen von Lehrplänen erstellen (alle Daten werden übernommen)

== Ziele

Ziel ist eine funktionierende, benutzerfreundliche, übersichtliche
Anwendung zur Darstellung von Lehrplänen. Schulintern können die Stammdaten
der Lehrpläne von einem Lehrplanadministrator schnell und unkompliziert geändert und gelöscht werden.
Weiters können bestehende Lehrpläne kopiert und so auf einfache Weise Folgeversionen erstellt werden.
Das Programm mit seinen Grundfunktionalitäten wie das Anzeigen aller Lehrplandaten sowie das Löschen und Ändern einiger
Daten wird bis Ende des Schuljahres fertiggestellt sein.

== Rahmenbedingungen

* Entwicklung mit Quarkus und Angular
* Übersichtliche Dokumentation mittels YouTrack
* Anwendung bis Ende des Schuljahres fertiggestellt

== Systemarchitektur

